export const FETCH_USERS_REQUEST = 'admin/FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'admin/FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'admin/FETCH_USERS_FAILURE';

export const CREATE_USER_REQUEST = 'admin/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'admin/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'admin/CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'admin/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'admin/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'admin/UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'admin/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'admin/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'admin/DELETE_USER_FAILURE';