export const FETCH_LOCATIONS_REQUEST = 'location/FETCH_LOCATIONS_REQUEST';
export const FETCH_LOCATIONS_SUCCESS = 'location/FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'location/FETCH_LOCATIONS_FAILURE';

export const FETCH_LOCATION_REQUEST = 'location/FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_SUCCESS = 'location/FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILURE = 'location/FETCH_LOCATION_FAILURE';

export const CREATE_LOCATION_REQUEST = 'location/CREATE_LOCATION_REQUEST';
export const CREATE_LOCATION_SUCCESS = 'location/CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAILURE = 'location/CREATE_LOCATION_FAILURE';

export const UPDATE_LOCATION_REQUEST = 'location/UPDATE_LOCATION_REQUEST';
export const UPDATE_LOCATION_SUCCESS = 'location/UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'location/UPDATE_LOCATION_FAILURE';

export const DELETE_LOCATION_REQUEST = 'location/DELETE_LOCATION_REQUEST';
export const DELETE_LOCATION_SUCCESS = 'location/DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAILURE = 'location/DELETE_LOCATION_FAILURE';